### ISSUE TITLE
Random example does not introduce the main function

### ISSUE THREAD

**Issue by vlvagerviwager** [evancz/elm-architecture-tutorial#117]
The [Random example](https://github.com/evancz/elm-architecture-tutorial/blob/master/examples/04-random.elm) includes this line in Phase 1: 

>At this point, it is possible to wire it all up and take a look. You can click the <button>, but nothing happens. Let's fix that!

However, there is no main function, so after following the steps, compiling it, and opening the HTML file, there is nothing in the browser. 

- OS: macOS Sierra 10.12.4
- Elm version: 0.18.0

**Comment by evancz** [comment]
The latest version of https://guide.elm-lang.org/ introduces `main` much earlier in the text.

The first mention is in [this example](https://guide.elm-lang.org/architecture/buttons.html). I think the latest version of the guide also uses a different style. Instead of presenting the code as if we are writing as the book progresses, the book now examines code snippets from the overall example without suggesting that we are actively putting them together. There is also an `Edit` button on each example, so you can always start from a working version.
